apiVersion: v1
kind: Service
metadata:
  name: appointments-api-service
spec:
  selector:
    app: appointments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32002
  type: NodePort