# Retrieve all appointments
GET http://localhost:5107/api/appointments
Accept: application/json
###

# Create a new appointment
POST http://localhost:5107/api/appointments
Content-Type: application/json

{
  "patientId": "987e6543-e21b-34d3-c456-426614174111",
  "doctorId": "654e3210-e54b-56d3-d456-426614174222",
  "slot": {
    "start": "2025-02-01T10:00:00",
    "end": "2025-02-01T11:00:00"
  },
  "location": {
    "roomNumber": "101",
    "building": "Main"
  },
  "purpose": "General Consultation"
}
###

# Retrieve patient appointments
GET http://localhost:5107/api/Appointments/GetAppointmentsByPatientId/0bc84d37-5bf6-439f-9c2e-d94ed1e3beee
Accept: application/json
###